### ISSUE TITLE
Sex associated proteins among 5000+ protein targets

### ISSUE THREAD

**Issue by Shicheng-Guo** [SomaLogic/SomaLogic-Data#1]
Dear Team, 

I am wondering do you have a protein list that are sex/gender(female/male) associated proteins among 5000+ protein targets in Somalogic data?  I'd like to use them as one of the criterions in quality control.

Thanks. 

Shicheng

**Comment by stufield** [comment]
Hi @Shicheng-Guo,

Thanks for your question!

At first glance I think this question is appropriate for our Global Scientific Engagement Team, which can be reached at <techsupport@somalogic.com>. 

That being said, there is a nice workflow/article on our [SomaDataIO](https://github.com/SomaLogic/SomaDataIO) repository on the website [here](https://somalogic.github.io/SomaDataIO/articles/stat-two-group-comparison.html), which shows univariate statistics table based on the `Sex` variable in the `example_data` data set. You can also look at the [Binary Classification](https://somalogic.github.io/SomaDataIO/articles/stat-binary-classification.html) workflow to see how a model based on these top univariate proteins performs.

I'd recommend working yourself through the example and generating your own list of empirical Gender candidate analytes and then orthogonally validating that shortlist with known biology, e.g. "Pregnancy Zone Protein" seems a likely candidate for gender specific expression.

I'm looping in @wschwarzmann here so he can take over if you need any further follow up.

**Comment by amanda-hi** [comment]
Hi @Shicheng-Guo, I hope Stu was able to answer your question! Because this issue has been quiet for some time, I am going to close it. However, if you'd like more information or clarification, please let me know and I can re-open the issue or create a new one to continue the conversation. Thanks!
